accounts:
  - name: Alex
    coins: ["20000cgas", "200000000cht"]
  - name: Austin
    coins: ["10000cgas", "100000000cht"]
validator:
  name: Alex
  staked: "100000000cht"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: Austin
  coins: ["5cgas", "100000cht"]
  #host:
  # rpc:  ":26659"
  # p2p:  ":26655"
  # prof:  ":6060"
  # grpc:  ":9090"
  # api:  ":1318"
genesis:
  chain_id: "morocco-1"
  app_state:
    staking:
      params:
        bond_denom: "cht"
    mint:
      params:
        mint_denom: "cht"
    crisis:
      constant_fee:
        denom: "cgas"
    gov:
      deposit_params:
          min_deposit:
            amount: "100000000"
            denom: "cht"
  