accounts:
  - name: Alex
    coins: ["20000cgas", "200000000cht"]
  - name: Austin
    coins: ["10000cgas", "100000000cht"]
validator:
  name: Alex
  staked: "100000000cht"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: Austin
  coins: ["5cgas", "100000cht"]
